### ISSUE TITLE
Vertex color don't rip correctly

### ISSUE THREAD

**Issue by GalacticFairy** [Razmoth/SRStudio#1]
A lot of the characters don't rip with their vertex colors exactly right or just have it missing entirely for faces (this is also an issue with BH3 Studio)

from SRStudio
![image](https://user-images.githubusercontent.com/105132829/182932021-f0143e39-e7c2-4f0f-9c32-d1dbada42e99.png)

from older leaks of the game
![image](https://user-images.githubusercontent.com/105132829/182932032-2eec2542-9a89-4205-a75f-5c735e0dfa10.png)

**Comment by Razmoth** [comment]
Greetings.

Thank you for reporting this issue, will investigate it further.

**Comment by Razmoth** [comment]
The issue will be discussed on [HoYoStudio](https://github.com/Razmoth/HoYoStudio).
